@echo off
set "GIT_PATH=C:\Program Files\Git\bin\git.exe"

echo Initializing Git...
"%GIT_PATH%" init
echo Adding files...
"%GIT_PATH%" add .
echo Committing...
"%GIT_PATH%" commit -m "Mobile UI Polish & Stark-tech Refinements - Matkotech Final Polish"
echo Adding remote...
"%GIT_PATH%" remote add origin https://github.com/priyanshulohar8233/Matkotect-Webiste.git 2>nul
echo Setting branch to main...
"%GIT_PATH%" branch -M main
echo Pushing to GitHub...
"%GIT_PATH%" push -u origin main
echo Done!
pause
